# Generated by Django 3.1.6 on 2021-02-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import wsc_django.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.SmallIntegerField(default=0, verbose_name='角色，二进制运算进行校验')),
                ('permissions', models.BigIntegerField(default=0, verbose_name='权限，二进制运算进行校验')),
                ('status', models.SmallIntegerField(default=1, verbose_name='员工状态，0：删除，1：正常')),
                ('position', models.CharField(max_length=16, verbose_name='员工职位')),
                ('entry_date', models.DateField(verbose_name='员工入职时间')),
                ('remark', models.CharField(max_length=32, verbose_name='备注')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'staff',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
        migrations.CreateModel(
            name='StaffApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1, verbose_name='申请状态,-1:未申请，1；申请中，2：已通过')),
                ('expired', models.SmallIntegerField(default=0, verbose_name='申请信息是否过期，0：未过期，1：已过期')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='对应的店铺对象')),
            ],
            options={
                'verbose_name': '员工申请表',
                'verbose_name_plural': '员工申请表',
                'db_table': 'staff_apply',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
