# Generated by Django 3.1.6 on 2021-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210206_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='entry_date',
            field=models.DateField(auto_now_add=True, verbose_name='员工入职时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(default='无', max_length=16, verbose_name='员工职位'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='remark',
            field=models.CharField(default='', max_length=32, verbose_name='备注'),
        ),
    ]
