# Generated by Django 3.1.6 on 2021-02-24 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='客户新增日期')),
                ('consume_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='消费金额')),
                ('consume_count', models.IntegerField(default=0, verbose_name='消费次数')),
                ('point', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='积分')),
                ('remark', models.CharField(default='', max_length=64, verbose_name='备注')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='客户对应的店铺对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='客户对应的用户对象')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point_change', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='积分变更量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('current_point', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='历史时刻当前积分')),
                ('type', models.SmallIntegerField(default=0, verbose_name='变更类型(预留)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='对应客户对象')),
            ],
            options={
                'verbose_name': '客户历史积分',
                'verbose_name_plural': '客户历史积分',
                'db_table': 'customer_point',
            },
        ),
    ]
