# Generated by Django 3.1.6 on 2021-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='客户新增日期')),
                ('consume_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='消费金额')),
                ('consume_count', models.IntegerField(default=0, verbose_name='消费次数')),
                ('point', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='积分')),
                ('remark', models.CharField(default='', max_length=64, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point_change', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='积分变更量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('current_point', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='历史时刻当前积分')),
                ('type', models.SmallIntegerField(default=0, verbose_name='变更类型(预留)')),
            ],
            options={
                'verbose_name': '客户历史积分',
                'verbose_name_plural': '客户历史积分',
                'db_table': 'customer_point',
            },
        ),
        migrations.CreateModel(
            name='MineAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.IntegerField(verbose_name='省份编号')),
                ('city', models.IntegerField(verbose_name='城市编号')),
                ('county', models.IntegerField(verbose_name='区编号')),
                ('address', models.CharField(max_length=64, verbose_name='详细地址')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='纬度')),
                ('name', models.CharField(max_length=32, verbose_name='顾客姓名')),
                ('sex', models.SmallIntegerField(default=0, verbose_name='顾客性别,0:未知1:男2:女')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='顾客手机号')),
                ('default', models.SmallIntegerField(default=0, verbose_name='是否为默认地址')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态,0:删除1:正常')),
            ],
            options={
                'verbose_name': '我的地址',
                'verbose_name_plural': '我的地址',
                'db_table': 'mine_address',
            },
        ),
    ]
