# Generated by Django 3.1.6 on 2021-03-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20210303_1158'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.IntegerField(verbose_name='省份编号')),
                ('city', models.IntegerField(verbose_name='城市编号')),
                ('county', models.IntegerField(verbose_name='区编号')),
                ('address', models.CharField(max_length=64, verbose_name='详细地址')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='纬度')),
                ('name', models.CharField(max_length=32, verbose_name='顾客姓名')),
                ('sex', models.SmallIntegerField(default=0, verbose_name='顾客性别,0:未知1:男2:女')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='顾客手机号')),
                ('default', models.SmallIntegerField(default=0, verbose_name='是否为默认地址')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态,0:删除1:正常')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='shop.shop', verbose_name='顾客ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='顾客ID')),
            ],
            options={
                'verbose_name': '我的地址',
                'verbose_name_plural': '我的地址',
                'db_table': 'mine_address',
            },
        ),
    ]
