# Generated by Django 3.1.6 on 2021-03-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210302_1002'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productgroup',
            table='product_group',
        ),
        migrations.AlterModelTable(
            name='productpicture',
            table='product_picture',
        ),
    ]
