# Generated by Django 3.1.6 on 2021-02-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210211_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productgroup', verbose_name='该商品分组的父级ID'),
        ),
    ]
