# Generated by Django 3.1.6 on 2021-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210211_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='level',
            field=models.SmallIntegerField(null=True, verbose_name='商品分组级别'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='sort',
            field=models.IntegerField(null=True, verbose_name='商品分组排序'),
        ),
    ]
