# Generated by Django 3.1.6 on 2021-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.SmallIntegerField(verbose_name='操作类型')),
                ('operate_content', models.CharField(default='', max_length=512, verbose_name='操作内容')),
            ],
            options={
                'verbose_name': '设置模块操作日志',
                'verbose_name_plural': '设置模块操作日志',
                'db_table': 'config_log',
            },
        ),
        migrations.CreateModel(
            name='OperateLogUnify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_module', models.SmallIntegerField(verbose_name='操作模块')),
                ('log_id', models.IntegerField(verbose_name='子模块的操作记录id')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'db_table': 'operate_log_unify',
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.SmallIntegerField(verbose_name='操作类型')),
                ('operate_content', models.CharField(default='', max_length=512, verbose_name='操作内容')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('order_id', models.IntegerField(verbose_name='订单id')),
            ],
            options={
                'verbose_name': '订单日志',
                'verbose_name_plural': '订单日志',
                'db_table': 'order_log',
            },
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.SmallIntegerField(verbose_name='操作类型')),
                ('operate_content', models.CharField(default='', max_length=512, verbose_name='操作内容')),
            ],
            options={
                'verbose_name': '货品日志',
                'verbose_name_plural': '货品日志',
                'db_table': 'product_log',
            },
        ),
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.SmallIntegerField(verbose_name='操作类型')),
                ('operate_content', models.CharField(default='', max_length=512, verbose_name='操作内容')),
            ],
            options={
                'verbose_name': '玩法日志',
                'verbose_name_plural': '玩法日志',
                'db_table': 'promotion_log',
            },
        ),
        migrations.CreateModel(
            name='StaffLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.SmallIntegerField(verbose_name='操作类型')),
                ('operate_content', models.CharField(default='', max_length=512, verbose_name='操作内容')),
                ('staff_id', models.IntegerField(verbose_name='被操作的员工ID')),
            ],
            options={
                'verbose_name': '员工日志',
                'verbose_name_plural': '员工日志',
                'db_table': 'staff_log',
            },
        ),
    ]
