# Generated by Django 3.1.6 on 2021-04-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210408_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='operator_id',
            new_name='operator',
        ),
    ]
