# Generated by Django 3.1.6 on 2021-04-08 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0003_auto_20210408_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='operator',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.CreateModel(
            name='OperateLogUnify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_module', models.SmallIntegerField(verbose_name='操作模块')),
                ('log_id', models.IntegerField(verbose_name='子模块的操作记录id')),
                ('operator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'db_table': 'operate_log_unify',
            },
        ),
    ]
