# Generated by Django 3.1.6 on 2021-04-13 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0005_configlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop_id', models.IntegerField(verbose_name='商铺id')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operate_type', models.SmallIntegerField(verbose_name='操作类型')),
                ('operate_content', models.CharField(default='', max_length=512, verbose_name='操作内容')),
                ('operator', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '玩法日志',
                'verbose_name_plural': '玩法日志',
                'db_table': 'promotion_log',
            },
        ),
    ]
