# Generated by Django 3.1.6 on 2021-02-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('shop', '0001_initial'),
        ('order', '0001_initial'),
        ('delivery', '0002_deliveryconfig_pickperiodconfigline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='对应的店铺对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='订单对应客户对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='订单对应配送记录对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='订单对应的店铺对象'),
        ),
    ]
