# Generated by Django 3.1.6 on 2021-06-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('groupon', '0003_groupon_shop'),
        ('order', '0002_orderdetail_product'),
        ('customer', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='对应的店铺对象'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='对应的订单对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='订单对应客户对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery', verbose_name='订单对应配送记录对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='groupon_attend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groupon.grouponattend', verbose_name='订单对应拼团参与对象'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='订单对应的店铺对象'),
        ),
    ]
