# Generated by Django 3.1.6 on 2021-06-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210606_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='added',
            field=models.CharField(max_length=50, null=True, verbose_name='补充说明'),
        ),
    ]
