# Generated by Django 3.1.6 on 2021-02-23 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wsc_django.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpenid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_openid', models.CharField(max_length=64, verbose_name='用户在对应公众号的openid')),
                ('mp_appid', models.CharField(max_length=64, verbose_name='公众号的appid（特殊的，对于利楚服务商支付，格式为lcwx-[shop_id]）')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useropenid', to=settings.AUTH_USER_MODEL, verbose_name='对应的用户对象')),
            ],
            options={
                'verbose_name': '用户openid',
                'verbose_name_plural': '用户openid',
                'db_table': 'user_openid',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
