# Generated by Django 3.1.6 on 2021-02-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import wsc_django.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrowseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始浏览时间')),
                ('duration', models.IntegerField(verbose_name='停留时间')),
                ('pre_page_name', models.CharField(max_length=32, verbose_name='上一页名称')),
                ('next_page_name', models.CharField(max_length=32, verbose_name='下一页名称')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='对应货品对象')),
            ],
            options={
                'verbose_name': '货品访问记录',
                'verbose_name_plural': '货品访问记录',
                'db_table': 'prodoct_browse_record',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
