# Generated by Django 3.1.6 on 2021-03-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvuv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productbrowserecord',
            table='product_browse_record',
        ),
    ]
