# Generated by Django 3.1.6 on 2021-02-06 08:29

from django.db import migrations, models
import wsc_django.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.SmallIntegerField(default=2, verbose_name='配送方式')),
                ('company', models.CharField(max_length=32, verbose_name='快递公司,仅在配送方式为快递时才有')),
                ('express_num', models.CharField(max_length=32, verbose_name='快递单号,仅在配送方式为快递时才有')),
            ],
            options={
                'verbose_name': '配送记录',
                'verbose_name_plural': '配送记录',
                'db_table': 'delivery',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
