# Generated by Django 3.1.6 on 2021-02-19 09:12

from django.db import migrations, models
import django.db.models.deletion
import wsc_django.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfig',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.shop', verbose_name='店铺id')),
                ('home_on', models.BooleanField(default=True, verbose_name='配送模式是否开启')),
                ('home_minimum_order_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='配送模式起送金额')),
                ('home_delivery_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='配送模式配送费')),
                ('home_minimum_free_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='配送模式免配送费最小金额')),
                ('pick_on', models.BooleanField(default=True, verbose_name='自提模式是否开启')),
                ('pick_service_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='自提模式服务费')),
                ('pick_minimum_free_amount', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='自提模式免服务费最小金额')),
                ('pick_today_on', models.BooleanField(default=True, verbose_name='今天自提是否开启')),
                ('pick_tomorrow_on', models.BooleanField(default=True, verbose_name='明天自提是否开启')),
            ],
            options={
                'verbose_name': '配送配置',
                'verbose_name_plural': '配送配置',
                'db_table': 'delivery_config',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
        migrations.CreateModel(
            name='PickPeriodConfigLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.CharField(max_length=16, verbose_name='自提起始时间')),
                ('to_time', models.CharField(max_length=16, verbose_name='自提终止时间')),
                ('delivery_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryconfig', verbose_name='订单配送配置对象')),
            ],
            options={
                'verbose_name': '自提时间段',
                'verbose_name_plural': '自提时间段',
                'db_table': 'pick_period_config_line',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
