# Generated by Django 3.1.6 on 2021-02-06 08:29

from django.db import migrations, models
import wsc_django.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=2, verbose_name='店铺状态 0: 已关闭 1: 正常,审核通过, 2: 审核中, 3: 已拒绝')),
                ('shop_name', models.CharField(max_length=128, verbose_name='店铺名称')),
                ('shop_code', models.CharField(default='', max_length=16, verbose_name='随机字符串，用于代替id')),
                ('shop_phone', models.CharField(default='', max_length=32, verbose_name='联系电话')),
                ('shop_img', models.CharField(default='', max_length=300, verbose_name='门头照片')),
                ('business_licence', models.CharField(default='', max_length=300, verbose_name='营业执照')),
                ('shop_address', models.CharField(default='', max_length=100, verbose_name='店铺地址')),
                ('shop_country', models.IntegerField(default=0, verbose_name='店铺所在国家')),
                ('shop_province', models.IntegerField(default=0, verbose_name='店铺所在省份')),
                ('shop_city', models.IntegerField(default=0, verbose_name='店铺所在城市')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='店铺创建时间')),
                ('cerify_active', models.SmallIntegerField(default=1, verbose_name='是否认证,1:是,0:否')),
                ('shop_verify_type', models.SmallIntegerField(default=1, verbose_name='店铺类型,0:企业,1:个人')),
                ('shop_verify_content', models.CharField(max_length=200, verbose_name='认证内容(公司名称)')),
                ('pay_active', models.SmallIntegerField(default=1, verbose_name='是否开通线上支付,1:是,0:否')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'shop',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
