# Generated by Django 3.1.6 on 2021-02-24 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(default=2, verbose_name='商铺状态 0: 已关闭 1: 正常,审核通过, 2: 审核中, 3: 已拒绝')),
                ('shop_name', models.CharField(max_length=128, verbose_name='商铺名称')),
                ('shop_code', models.CharField(default='', max_length=16, verbose_name='随机字符串，用于代替id')),
                ('shop_phone', models.CharField(default='', max_length=32, verbose_name='联系电话')),
                ('shop_img', models.CharField(default='', max_length=300, verbose_name='门头照片')),
                ('business_licence', models.CharField(default='', max_length=300, verbose_name='营业执照')),
                ('shop_address', models.CharField(default='', max_length=100, verbose_name='商铺地址')),
                ('shop_county', models.IntegerField(default=0, verbose_name='商铺所在国家编号')),
                ('shop_province', models.IntegerField(default=0, verbose_name='商铺所在省份编号')),
                ('shop_city', models.IntegerField(default=0, verbose_name='商铺所在城市编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='商铺创建时间')),
                ('description', models.CharField(default='', max_length=256, verbose_name='商铺描述')),
                ('inviter_phone', models.CharField(default='', max_length=32, verbose_name='推荐人手机号')),
                ('cerify_active', models.SmallIntegerField(default=1, verbose_name='是否认证,1:是,0:否')),
                ('shop_verify_type', models.SmallIntegerField(default=1, verbose_name='商铺类型,0:企业,1:个人')),
                ('shop_verify_content', models.CharField(max_length=200, verbose_name='认证内容(公司名称)')),
                ('pay_active', models.SmallIntegerField(default=1, verbose_name='是否开通线上支付,1:是,0:否')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商铺老板')),
            ],
            options={
                'verbose_name': '商铺',
                'verbose_name_plural': '商铺',
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='HistoryRealName',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.shop', verbose_name='对应的店铺id')),
                ('realname', models.CharField(max_length=32, verbose_name='历史真实姓名')),
            ],
            options={
                'verbose_name': '商铺创建者历史真实姓名',
                'verbose_name_plural': '商铺创建者历史真实姓名',
                'db_table': 'history_realname',
            },
        ),
        migrations.CreateModel(
            name='ShopRejectReason',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.shop', verbose_name='对应的店铺id')),
                ('reject_reason', models.CharField(default='', max_length=256, verbose_name='拒绝理由')),
            ],
            options={
                'verbose_name': '商铺拒绝理由',
                'verbose_name_plural': '商铺拒绝理由',
                'db_table': 'shop_reject_reason',
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['shop_code'], name='ux_shop_code'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['super_admin'], name='ix_super_admin'),
        ),
    ]
