# Generated by Django 3.1.6 on 2021-02-23 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20210219_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '商铺', 'verbose_name_plural': '商铺'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='商铺创建时间'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='商铺描述'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_address',
            field=models.CharField(default='', max_length=100, verbose_name='商铺地址'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_city',
            field=models.IntegerField(default=0, verbose_name='商铺所在城市编号'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_county',
            field=models.IntegerField(default=0, verbose_name='商铺所在国家编号'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=128, verbose_name='商铺名称'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_province',
            field=models.IntegerField(default=0, verbose_name='商铺所在省份编号'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_verify_type',
            field=models.SmallIntegerField(default=1, verbose_name='商铺类型,0:企业,1:个人'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='商铺状态 0: 已关闭 1: 正常,审核通过, 2: 审核中, 3: 已拒绝'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='super_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商铺老板'),
        ),
    ]
