# Generated by Django 3.1.6 on 2021-02-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210206_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='店铺描述'),
        ),
        migrations.AddField(
            model_name='shop',
            name='inviter_phone',
            field=models.CharField(default='', max_length=32, verbose_name='推荐人手机号'),
        ),
    ]
