# Generated by Django 3.1.6 on 2021-03-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210303_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrealname',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
