# Generated by Django 3.1.6 on 2021-02-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210207_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_country',
            new_name='shop_county',
        ),
    ]
