# Generated by Django 3.1.6 on 2021-03-08 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210303_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('smerchant_no', models.CharField(default='', max_length=15, verbose_name='商户号')),
                ('smerchant_name', models.CharField(default='', max_length=100, verbose_name='商户名')),
                ('smerchant_type_id', models.CharField(default='', max_length=15, verbose_name='商户类别id')),
                ('smerchant_type_name', models.CharField(default='', max_length=81, verbose_name='商户类别名')),
                ('pos_id', models.CharField(default='', max_length=9, verbose_name='柜台号')),
                ('terminal_id1', models.CharField(default='', max_length=50, verbose_name='终端号1')),
                ('terminal_id2', models.CharField(default='', max_length=50, verbose_name='终端号2')),
                ('access_token', models.CharField(default='', max_length=32, verbose_name='扫呗access_token')),
                ('clearing_rate', models.FloatField(default=2.8, verbose_name='商户的清算费率,利楚默认是千分之2.8，建行是0')),
                ('clearing_account_id', models.IntegerField(default=0, verbose_name='商户的清算账号ID')),
                ('channel_type', models.SmallIntegerField(default=0, verbose_name='支付渠道, 1:利楚, 2:建行')),
                ('pub_key', models.CharField(max_length=500, verbose_name='账户公匙')),
                ('province', models.CharField(default='Hubei', max_length=32, verbose_name='用户所在省份')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='店铺对象')),
            ],
            options={
                'verbose_name': '支付渠道',
                'verbose_name_plural': '支付渠道',
                'db_table': 'pay_channel',
            },
        ),
    ]
