# Generated by Django 3.1.6 on 2021-02-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import wsc_django.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20210206_1629'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStorageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_type', models.SmallIntegerField(default=1, verbose_name='操作人类型,1:员工,2:客户')),
                ('create_time', models.DateTimeField(verbose_name='货品库存变更记录创建时间')),
                ('type', models.SmallIntegerField(default=2, verbose_name='货品库存记录变更类型')),
                ('change_storage', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='本次操作变更量')),
                ('current_storage', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='历史时刻当前库存')),
                ('order_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='对应货品对象')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='对应的店铺对象')),
            ],
            options={
                'verbose_name': '货品库存变更记录',
                'verbose_name_plural': '货品库存变更记录',
                'db_table': 'prodoct_storage_record',
            },
            bases=(models.Model, wsc_django.utils.models.TimeBaseMixin),
        ),
    ]
