# Generated by Django 3.1.6 on 2021-03-02 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productstoragerecord',
            table='product_storage_record',
        ),
    ]
