# Generated by Django 3.1.6 on 2021-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210308_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('custom_title_name', models.CharField(default='', max_length=64, verbose_name='自定义分享标题名称')),
                ('custom_share_description', models.CharField(default='', max_length=64, verbose_name='自定义分享描述')),
            ],
            options={
                'verbose_name': '分享设置',
                'verbose_name_plural': '分享设置',
                'db_table': 'share_setup',
            },
        ),
    ]
