# Generated by Django 3.1.6 on 2021-04-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_sharesetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('show_off_product', models.BooleanField(default=True, verbose_name='货品板块显示已下架货品')),
                ('new_order_voice', models.BooleanField(default=True, verbose_name='新订单语音提醒')),
                ('weixin_jsapi', models.BooleanField(default=False, verbose_name='是否开启微信支付')),
                ('on_delivery', models.BooleanField(default=True, verbose_name='是否开启货到付款')),
            ],
            options={
                'verbose_name': '一些杂乱的配置项',
                'verbose_name_plural': '一些杂乱的配置项',
                'db_table': 'some_config',
            },
        ),
    ]
