# Generated by Django 3.1.6 on 2021-04-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_paychannel'),
        ('product', '0003_auto_20210302_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='商品拼团价格')),
                ('from_datetime', models.DateTimeField(verbose_name='拼团活动开始时间')),
                ('to_datetime', models.DateTimeField(verbose_name='拼团活动结束时间')),
                ('groupon_type', models.SmallIntegerField(verbose_name='拼团活动类型 1:普通 2:老带新')),
                ('success_size', models.SmallIntegerField(default=1, verbose_name='成团人数')),
                ('quantity_limit', models.IntegerField(default=0, verbose_name='购买数量上限（限制每个订单的购买数量）')),
                ('success_limit', models.IntegerField(default=0, verbose_name='成团数量上限(限制单次活动的最大成团数量)')),
                ('attend_limit', models.IntegerField(default=0, verbose_name='参团数量上限(每个用户能参加同一拼团的次数)')),
                ('success_valid_hour', models.IntegerField(default=24, verbose_name='开团有效时间(超过次时间未成团的活动将自动解散)')),
                ('status', models.SmallIntegerField(default=1, verbose_name='拼团活动状态 1:启用 2:停用 3:过期')),
                ('succeeded_count', models.IntegerField(default=0, verbose_name='成团数')),
                ('succeeded_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='成团件数')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可以编辑')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='对应的货品对象')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='对应的店铺对象')),
            ],
            options={
                'verbose_name': '拼团活动',
                'verbose_name_plural': '拼团活动',
                'db_table': 'groupon',
            },
        ),
    ]
