# Generated by Django 3.1.6 on 2021-06-06 12:54

from django.db import migrations, models
import django.db.models.deletion
import promotion.abstract


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='商品拼团价格')),
                ('from_datetime', models.DateTimeField(verbose_name='拼团活动开始时间')),
                ('to_datetime', models.DateTimeField(verbose_name='拼团活动结束时间')),
                ('groupon_type', models.SmallIntegerField(verbose_name='拼团活动类型 1:普通 2:老带新')),
                ('success_size', models.SmallIntegerField(default=1, verbose_name='成团人数')),
                ('quantity_limit', models.IntegerField(default=0, verbose_name='购买数量上限（限制每个订单的购买数量）')),
                ('success_limit', models.IntegerField(default=0, verbose_name='成团数量上限(限制单次活动的最大成团数量)')),
                ('attend_limit', models.IntegerField(default=0, verbose_name='参团数量上限(每个用户能参加同一拼团的次数)')),
                ('success_valid_hour', models.IntegerField(default=24, verbose_name='开团有效时间(超过此时间未成团的活动将自动解散)')),
                ('status', models.SmallIntegerField(default=1, verbose_name='拼团活动状态 1:启用 2:停用 3:过期')),
                ('succeeded_count', models.IntegerField(default=0, verbose_name='成团数')),
                ('succeeded_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=13, verbose_name='成团件数')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可以编辑')),
            ],
            options={
                'verbose_name': '拼团活动',
                'verbose_name_plural': '拼团活动',
                'db_table': 'groupon',
            },
        ),
        migrations.CreateModel(
            name='GrouponAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('size', models.IntegerField(default=0, verbose_name='拼团当前参与人数')),
                ('anonymous_size', models.IntegerField(default=0, verbose_name='强制成团添加的匿名用户数量')),
                ('success_size', models.IntegerField(verbose_name='成团人数')),
                ('to_datetime', models.DateTimeField(verbose_name='拼团参与结束时间')),
                ('status', models.SmallIntegerField(default=0, verbose_name='拼团参与状态 -1: 超时未支付 0:已创建 1:拼团中 2:已成团 3:已失败')),
                ('failed_reason', models.CharField(default='', max_length=64, verbose_name='失败原因')),
                ('groupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon.groupon', verbose_name='拼团活动')),
            ],
            options={
                'verbose_name': '拼团参与表',
                'verbose_name_plural': '拼团参与表',
                'db_table': 'groupon_attend',
            },
            bases=(models.Model, promotion.abstract.AbstractPromotionRule),
        ),
        migrations.CreateModel(
            name='GrouponAttendDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_sponsor', models.BooleanField(default=True, verbose_name='是否是团长')),
                ('is_new_customer', models.BooleanField(default=False, verbose_name='是否是新用户')),
                ('status', models.SmallIntegerField(default=0, verbose_name='参团状态 -1:超时未支付 0:未支付 1:已支付')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='参与客户')),
                ('groupon_attend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupon.grouponattend', verbose_name='拼团参与')),
            ],
            options={
                'verbose_name': '拼团参与详情表',
                'verbose_name_plural': '拼团参与详情表',
                'db_table': 'groupon_attend_detail',
            },
        ),
    ]
