# Generated by Django 3.1.6 on 2021-06-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('groupon', '0002_groupon_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupon',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='对应的店铺对象'),
        ),
    ]
