"""
Django settings for wsc_django project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UTILS_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


#设置python导包环境
import sys
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))
sys.path.insert(1, UTILS_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pspe=jr1_77&m+zqzpyr@7$vl*@s$2v+d*=%0*lauoy+z936sr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 告知Django认证系统使用我们自定义的模型类。
AUTH_USER_MODEL = 'user.User'

# cookies相关
AUTH_COOKIE_EXPIRE_DAYS = 60*60*24*7

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方应用
    'rest_framework',
    'corsheaders', # cors
    'channels', # websocket

    # 本地应用
    'config.apps.ConfigConfig',
    'customer.apps.CustomerConfig',
    'dashboard.apps.DashboardConfig',
    'delivery.apps.DeliveryConfig',
    'groupon.apps.GrouponConfig',
    'logs.apps.LogsConfig',
    'order.apps.OrderConfig',
    'payment.apps.PaymentConfig',
    'printer.apps.PrinterConfig',
    'product.apps.ProductConfig',
    'promotion.apps.PromotionConfig',
    'pvuv.apps.PvuvConfig',
    'shop.apps.ShopConfig',
    'staff.apps.StaffConfig',
    'storage.apps.StorageConfig',
    'user.apps.UserConfig',
    'ws.apps.WsConfig',
    # 测试用
    'demo.apps.DemoConfig',
]

# 中间件
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'wsc_django.xMiddleware.middleware.MyMiddleware', # 测试使用，跳过登录
    # 'wsc_django.xMiddleware.middleware.ConfigMiddleware', # 请求前和响应后进行一些配置
]

ROOT_URLCONF = 'wsc_django.urls'

# 模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsc_django.wsgi.application'

# 缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "verify_codes": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "num_generate": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    "subscribe": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/10",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"

# Database数据库
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',  # 数据库主机
        'PORT': 3306,  # 数据库端口
        'USER': 'wsc_django',  # 数据库用户名
        'PASSWORD': 'wsc_django',  # 数据库用户密码
        'NAME': 'wsc_django',  # 数据库名字
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 指定ASGI的路由地址
ASGI_APPLICATION = 'wsc_django.routing.application'

# channels websocket
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('localhost', 6379)],
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# 本地语言
LANGUAGE_CODE = 'zh-hans'

# 时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'wsc_django.utils.exceptions.wsc_exception_handler', # 异常处理
}

# redis数据库相关
REDIS_SERVER = "localhost"
REDIS_PORT = "6379"
REDIS_PASSWORD = ""

# jwt相关配置
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1), # 有效期
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'users.utils.jwt_response_payload_handler', # 响应体格式
}

# 腾讯云短信
TENCENT_SMS_APPID = "1400515719"
TENCENT_SMS_APPKEY = "0351a7ac6e3f4be41a77dd4626792ea2"
# 云片短信
YUNPIAN_SYSTEM_APIKEY = "6149a117b1f6c6991232298eb078fb30"

# 微信公众号相关
MP_APPID = 'wx819299c9d4c7bd24'
MP_APPSECRET = 'f71da8ef954f3d09bfcf5f646a95bbc9'

# CORS
CORS_ORIGIN_WHITELIST = (
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://localhost:3030',
    'http://127.0.0.1:3030',
    'http://81.68.135.24:8000',
    'http://81.68.135.24:80',
    'http://81.68.135.24:3030',
    'ws://localhost:8000',
    'ws://127.0.0.1:8000',
)
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

# 利楚商务测试服务器
LCSW_CALLBACK_HOST = "http://127.0.0.1:8000"
LCSW_HANDLE_HOST = "https://pay.lcsw.cn/lcsw"
LCSW_INST_NO = "52100011"
LCSW_INST_KEY = "a6540e60532a4f5f9207536cdd37d83d"


# 前端商城域名
WSC_HOST_NAME = ""

# 七牛云相关
QINIU_ACCESS_KEY = "Pm0tzHLClI6iHqxdkCbwlSwHWZycbQoRFQwdqEI_"
QINIU_SECRET_KEY = "gCjIMVE_lpW7d2bjI-AdMXDKQeE1bdtKxRInBRTH"
QINIU_BUCKET_SHOP_IMG = "shopimg"
QINIU_SHOP_IMG_HOST = "http://img.senguo.cc/"

# 百度AI开放平台 10464550
BAIDU_APIKEY = "xZLWgNDVgLRh9iwIA2Xt6yM1"
BAIDU_SECRETKEY = "HO7m2a7eTGeM9rPfMc73REWy7KwYwSCR"

# cookie相关
AUTH_COOKIE_DOMAIN = "http://hzhst1314.cn"
AUTH_COOKIE_EXPIRE = 60*60*24*7